# Generated by Django 3.1.14 on 2022-10-28 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyapp', '0002_auto_20221027_2139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactor',
            new_name='Company',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='department',
            name='List_employee',
            field=models.ManyToManyField(default='', related_name='empl', to='skyapp.Employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='chief_employee',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='skyapp.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='EmployeeHistory',
        ),
    ]
