# Generated by Django 3.1.14 on 2022-10-28 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyapp', '0003_auto_20221027_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='List_employee',
            field=models.ManyToManyField(default=' ', related_name='empl', to='skyapp.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default='dev', on_delete=django.db.models.deletion.CASCADE, related_name='deparments', to='skyapp.department'),
        ),
    ]
