# Generated by Django 3.1.14 on 2022-10-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyapp', '0008_auto_20221027_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('view_employee_list', 'view_employee_list')]},
        ),
    ]
