# Generated by Django 3.1.14 on 2022-10-28 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('position', models.TextField()),
                ('salary', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('department', models.CharField(default='', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.TextField(default='')),
                ('cheif', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chief', to='skyit_app.employee')),
                ('employees', models.ManyToManyField(related_name='employees_dep_list', to='skyit_app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=225)),
                ('departments', models.ManyToManyField(to='skyit_app.Department')),
            ],
        ),
    ]
